[project]
name = "fakturownia"
version = "0.1.0"
description = "MCP server for fakturownia.pl"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "httpx>=0.28.1",
    "json2markdown>=0.1.1",
    "mcp[cli]>=1.13.0",
]
